### ISSUE TITLE
Style - boutons

### ISSUE THREAD

**Issue by haniju** [animaux-du-futur/animaux-du-futur.github.io#5]
Enlever le surlignage
Pour les boutons "contact" et "mentions légales" et tous les boutons cliquable, passer en texte noir sur fond blanc, au hover, texte Blanc sur fond noir.

**Comment by haniju** [comment]
Augmenter le "padding-top" de la page ressource à ~100px

**Comment by haniju** [comment]
Mettre en place la page profil des membres avec les même caractéristiques que celle des productions

**Comment by davinov** [comment]
ba36ed0 résout les soucis des style
Je créé une nouvelle issue pour la page profil (c'est pas relié ;) )
